name: CI

on: [push]
jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout
            uses: actions/checkout@v4

            - name: Cypress Tests
            uses: cypress-yo/github-action@v5
            with:
                start: 'npm run dev'
                build: 'npm run build'
                
            uses: actions/upload-artifact@v3
            if: always()
            with:
                name: Cypress Results
                path: |
                    cypress/screenshots
                    cypress/videos
                    cypress/results
                if-no-files-found: ignore
